// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfwpAWs-mFWgGOk9JwdxaGtNEPckF7uyM',
    appId: '1:899030552506:web:7a6b64073a7c1632f3d783',
    messagingSenderId: '899030552506',
    projectId: 'dzpos-9d561',
    authDomain: 'dzpos-9d561.firebaseapp.com',
    storageBucket: 'dzpos-9d561.appspot.com',
    measurementId: 'G-JY4NK8D5BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVqhvxfrqnyWPrRXpBUiU27FrDMsl_Rnk',
    appId: '1:899030552506:android:e7f788d056577076f3d783',
    messagingSenderId: '899030552506',
    projectId: 'dzpos-9d561',
    storageBucket: 'dzpos-9d561.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxkMuAKGuMUbeE1wFWn1i_CxoKAGyFUd0',
    appId: '1:899030552506:ios:1e2265b12803d3a6f3d783',
    messagingSenderId: '899030552506',
    projectId: 'dzpos-9d561',
    storageBucket: 'dzpos-9d561.appspot.com',
    iosClientId: '899030552506-9g6k7bcvv1fdlbdgkbh4msioscdp3t8q.apps.googleusercontent.com',
    iosBundleId: 'dz.goudjal.dzpos',
  );
}
